/**
 * @author daviddaniel.dubach
 */
public class Bancomat extends javax.swing.JFrame {

    /**
     * Creates new form Bancomat
     */
    public Bancomat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnZero = new javax.swing.JButton();
        btnFunctionOne = new javax.swing.JButton();
        btnFunctionTwo = new javax.swing.JButton();
        btnFunctionThree = new javax.swing.JButton();
        btnFunctionFour = new javax.swing.JButton();
        bntFunctionFive = new javax.swing.JButton();
        btnFunctionSix = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnOne.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnOne.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnOne, gridBagConstraints);

        btnTwo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnTwo.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnTwo, gridBagConstraints);

        btnThree.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnThree.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnThree, gridBagConstraints);

        btnFour.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFour.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFour, gridBagConstraints);

        btnFive.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFive.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFive, gridBagConstraints);

        btnSix.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnSix.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSix, gridBagConstraints);

        btnSeven.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnSeven.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSeven, gridBagConstraints);

        btnEight.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnEight.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnEight, gridBagConstraints);

        btnNine.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnNine.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnNine, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        btnZero.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnZero.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnZero, gridBagConstraints);

        btnFunctionOne.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFunctionOne.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFunctionOne, gridBagConstraints);

        btnFunctionTwo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFunctionTwo.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFunctionTwo, gridBagConstraints);

        btnFunctionThree.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFunctionThree.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFunctionThree, gridBagConstraints);

        btnFunctionFour.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFunctionFour.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFunctionFour, gridBagConstraints);

        bntFunctionFive.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        bntFunctionFive.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(bntFunctionFive, gridBagConstraints);

        btnFunctionSix.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnFunctionSix.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFunctionSix, gridBagConstraints);

        btnCancel.setBackground(new java.awt.Color(255, 0, 51));
        btnCancel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        getContentPane().add(btnCancel, gridBagConstraints);

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        getContentPane().add(btnClear, gridBagConstraints);

        btnEnter.setBackground(new java.awt.Color(0, 255, 0));
        btnEnter.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        btnEnter.setText("Enter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        getContentPane().add(btnEnter, gridBagConstraints);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bancomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bancomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bancomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bancomat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bancomat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bntFunctionFive;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnFunctionFour;
    private javax.swing.JButton btnFunctionOne;
    private javax.swing.JButton btnFunctionSix;
    private javax.swing.JButton btnFunctionThree;
    private javax.swing.JButton btnFunctionTwo;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
}
