import ch.bbzsogr.bi.exceptions.AccountCreationException;
import ch.bbzsogr.bi.exceptions.CardCreationException;
import ch.bbzsogr.bi.exceptions.EntitySaveException;

import java.io.IOException;

/**
 * @author daviddaniel.dubach
 */
public class DistinctIfDirectOrRest extends javax.swing.JFrame {

    Bancomat bancomat = new Bancomat();

    /**
     * Creates new form DistinctIfDirectOrRest
     */
    public DistinctIfDirectOrRest() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnDirect = new javax.swing.JButton();
        labelInformation = new javax.swing.JLabel();
        btnRest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bancomat");
        setBounds(new java.awt.Rectangle(900, 320, 0, 0));

        btnDirect.setText("Local");
        btnDirect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectActionPerformed(evt);
            }
        });

        labelInformation.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        labelInformation.setText("How would you like to access your ATM data?");

        btnRest.setText("Rest");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(93, 93, 93)
                                                .addComponent(btnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(115, 115, 115))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(labelInformation)
                                                .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(labelInformation)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDirect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnDirectActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        bancomat.setVisible(true);
    }

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        bancomat.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistinctIfDirectOrRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistinctIfDirectOrRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistinctIfDirectOrRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistinctIfDirectOrRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              try {
                new DistinctIfDirectOrRest().setVisible(true);
              } catch (CardCreationException e) {
                e.printStackTrace();
              } catch (AccountCreationException e) {
                e.printStackTrace();
              } catch (EntitySaveException e) {
                e.printStackTrace();
              } catch (IOException e) {
                e.printStackTrace();
              } catch (Exception e) {
                e.printStackTrace();
              }
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnDirect;
    private javax.swing.JButton btnRest;
    private javax.swing.JLabel labelInformation;
    // End of variables declaration
}
