/**
 * @author daviddaniel.dubach
 */
public class PrintedReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintedReceipt
     */
    public PrintedReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnAmountText = new javax.swing.JLabel();
        btnAmountValue = new javax.swing.JLabel();
        btnBankAccountBalanceText = new javax.swing.JLabel();
        btnBankAccountBalanceValue = new javax.swing.JLabel();
        btnCloseReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");
        setBounds(new java.awt.Rectangle(900, 320, 0, 0));

        btnAmountText.setText("Amount of withdrawal:");

        btnAmountValue.setText("jLabel1");

        btnBankAccountBalanceText.setText("Bankaccount balance:");

        btnBankAccountBalanceValue.setText("jLabel1");

        btnCloseReceipt.setText("Close");
        btnCloseReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAmountText)
                                        .addComponent(btnBankAccountBalanceText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCloseReceipt)
                                        .addComponent(btnBankAccountBalanceValue)
                                        .addComponent(btnAmountValue))
                                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAmountText)
                                        .addComponent(btnAmountValue))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBankAccountBalanceText)
                                        .addComponent(btnBankAccountBalanceValue))
                                .addGap(18, 18, 18)
                                .addComponent(btnCloseReceipt)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnCloseReceiptActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel btnAmountText;
    private javax.swing.JLabel btnAmountValue;
    private javax.swing.JLabel btnBankAccountBalanceText;
    private javax.swing.JLabel btnBankAccountBalanceValue;
    private javax.swing.JButton btnCloseReceipt;
    // End of variables declaration
}
